### ISSUE TITLE
[Enhancement] Additional Status Effects

### ISSUE THREAD

**Issue by Caeldeth** [hybrasyl/server#132]
Per previous discussions:

1. +/- Gold Gain - Am curious as to how would be implemented.  As a buff, seems exploitable by exchanging gold.
2. +/- Experience Gain
3. "Better" Hide - Rogues should be better at being invisible than Monks (cannot be detected by eisd, etc).  Possible scripting solution
4. Confusion - Casts random different spell than intended, or random target.  Possible scripting solution
5. Disorient - Current mob ability in DA - causes character to randomly spin in place briefly.  Possible scripting solution

**Comment by baughj** [comment]
1 and 2 are very easy to implement. 1 would be implemented to only impact gold drops from mobs. However: should +% gold impact groups based on a sum of +gain%? Or what? 

3 - could be additional condition, simplest way - or eisd et al need to simply take class + condition into account

4 - condition otherwise the script has to do a lot of stuff, "Confused" could just be a status and UseCastable et al take it into account.

5 - also condition? This is really just `Turn()` repeatedly.

**Comment by Caeldeth** [comment]
Closing Issue.  Status effects can now be created on demand, anything else can be handled by script.
