### ISSUE TITLE
[Enhancement] Remove PS Script, Implement Folder Creation in Server Code

### ISSUE THREAD

**Issue by moseleyc** [hybrasyl/server#139]
On Server initialization check for the required folders, if they dont exist they should be created.

**Comment by moseleyc** [comment]
Will work on this.

**Comment by moseleyc** [comment]
Since we are incorporating the folder creation into the server code, would you prefer:

1) To have the server load bare-minimum example XML's if no files are found in the folders required for the server to even start (specifically this appears to be at least one Nation, and one Map XML must exist). This allows for someone to login, but doesn't provide anything else really.
2) Have no files load if no files are found in the folders required...thus requiring the user to exit the server (potentially twice, as the user is notified first only about the nation file, and then once that's "fixed", notifies about the map file)
3) Have all example files load if the individual folders don't have any files in them (essentially providing a working server, with minimum needs provided)

**Comment by baughj** [comment]
#2, personally. You can't run the server without manual intervention anyway because you must have a binary map file in addition to a map XML file, and we do not distribute the binary map files.

In the future the installer will take care of this kind of stuff, or at least tell the user what to do.

It seems like you should be able to process all the requirements at the end - create all needed directories if they don't exist, check to see if bare minimum xml exists (check to see if a nation and map exist with a valid map file) and then warn the user (maybe via popup window)?

**Comment by moseleyc** [comment]
Okay. I have proceeded under the '#2' assumption. Given that this should be handled in the future by an installer.

**Comment by baughj** [comment]
For now the 0.7.0 readme will point people to the community database & contain instructions for checking out and using it, which will work around this issue.
